Position models
MuonPi/muondetector pull request #83
Opened 2022-07-18 23:28 UTC by hangeza

PR to merge all the functionality of position model handling into dev

2022-07-22 08:48 UTC, dtreffenstaedt requested changes
Fix all comments
Use clang-tidy
Use clang-format

2022-07-22 08:48 UTC, dtreffenstaedt commented on daemon/include/daemon.h
> +    Property<UbxDopStruct> currentDOP {};
Fix naming of these class members.

2022-07-22 08:48 UTC, dtreffenstaedt commented on daemon/include/daemon.h
> +    //    QMap<QString, Property> propertyMap;
Do not uncomment code. Remove instead.

2022-07-22 08:48 UTC, dtreffenstaedt commented on daemon/include/utility/kalman_gnss_filter.h
> +    [[nodiscard]] auto valid() const -> bool { return (m_variance >= 0.); }
Move implementations to the source file.

2022-07-22 08:48 UTC, dtreffenstaedt commented on daemon/src/daemon.cpp
> +void Daemon::onGpsPropertyUpdatedGeodeticPos(const GnssPosStruct& pos)
This function is way too long and complex. Split it into smaller parts to make it readable and maintainable.

2022-07-22 08:48 UTC, dtreffenstaedt commented on daemon/src/daemon.cpp
> +*/
Do not comment code. Remove instead.

2022-07-22 08:48 UTC, dtreffenstaedt commented on daemon/src/daemon.cpp
> +*/
Do not comment code. Remove instead.

2022-07-22 08:48 UTC, dtreffenstaedt commented on daemon/src/daemon.cpp
> +        //propertyMap["fixStatus"] = Property("fixStatus", QString::fromLocal8Bit(Gnss::FixType::name[data]));
Do not comment code. Remove instead.

2022-07-22 08:48 UTC, dtreffenstaedt commented on daemon/src/daemon.cpp
> +        //propertyMap["events"] = Property("events", (quint16)data);
Do not comment code. Remove instead.

2022-07-22 08:48 UTC, dtreffenstaedt commented on daemon/src/daemon.cpp
> +        //propertyMap["clkDrift"] = Property("clkDrift", (qint32)data);
Do not comment code. Remove instead.

2022-07-22 08:48 UTC, dtreffenstaedt commented on daemon/src/daemon.cpp
> +        //propertyMap["clkBias"] = Property("clkBias", (qint32)data);
Do not comment code. Remove instead.

2022-07-22 08:48 UTC, dtreffenstaedt commented on daemon/src/daemon.cpp
> +            //sendGeodeticPos(config.position_mode_config.static_position.getPosStruct());
Do not comment code. Remove instead.

2022-07-22 08:48 UTC, dtreffenstaedt commented on daemon/src/daemon.cpp
> +    switch (config.position_mode_config.mode) {
This does not need to be a switch statement. It only has one case.

2022-07-22 08:48 UTC, dtreffenstaedt commented on daemon/src/utility/kalman_gnss_filter.cpp
> +    if (accuracy < c_min_accuracy)
Missing curly braces. Do not add statements without them.

2022-07-22 08:48 UTC, dtreffenstaedt commented on daemon/src/utility/kalman_gnss_filter.cpp
> +    m_lat = m_lng = m_alt = 0.;
No.

2022-07-22 08:48 UTC, dtreffenstaedt commented on gui/qml/CustomMap.qml
> +    signal coordinateSignal(double lat, double lon)
Keep the order of parameters consistent across the codebase.
Ideally use a struct instead.

2022-07-22 08:48 UTC, dtreffenstaedt commented on gui/src/map.cpp
> +#include <muondetector_structs.h>
Use double quotes instead of angle brackets for local includes.

2022-07-22 08:48 UTC, dtreffenstaedt commented on gui/src/map.cpp
> +    double pos_error { std::sqrt(pos.hAcc * pos.hAcc + pos.vAcc * pos.vAcc) };
Make this const.

2022-07-22 08:48 UTC, dtreffenstaedt commented on library/include/muondetector_structs.h
> +*/
Do not comment code. Remove instead.

2022-07-22 10:19 UTC, hangeza commented
Thanks for the review. Will try to fix all marked items. However, clang-format was applied regularly, so the PR should not have issues with this.

2022-07-22 10:24 UTC, hangeza commented on daemon/src/utility/kalman_gnss_filter.cpp
> +    m_lat = m_lng = m_alt = 0.;
I like the readability of such in-line assignments. Is there a good reason, not to do this?

2022-07-23 13:19 UTC, merged

2022-07-23 13:44 UTC, hangeza commented
I was wrongly merging position-models into dev. Intention was just to merge dev into position-models to sync both branches but fucked it up. Now the branch is merged and i have no idea how to revert it. Advice appreciated...
I think, however, that all but one item marked in the review of @dtreffenstaedt were settled, so merging shouldn't have done harm.

2022-07-24 06:51 UTC, dtreffenstaedt commented
All items should have been fixed.

2022-07-24 10:30 UTC, hangeza commented
Well, all but this [one](https://github.com/MuonPi/muondetector/pull/83#discussion_r927516321), which i don't understand that it is an issue. Could you elaborate on this?

2022-07-24 10:37 UTC, hangeza commented
As i understand now, the PR was closed but the branch "position-models" is NOT merged into dev. How should we proceed? Is it possible to reopen the PR?